"""Added data to tables

Revision ID: 2574aa5671cf
Revises: 123
Create Date: 2022-01-10 01:03:55.222267

"""
from datetime import datetime

from alembic import op
from sqlalchemy import orm

from homework12.models import (HomeworkResultTable, HomeworkTable,
                               StudentTable, TeacherTable)

# revision identifiers, used by Alembic.
revision = '2574aa5671cf'
down_revision = 'd95c0cfd98d9'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    student_first = StudentTable(name='Anakin', surname='Skywalker')
    student_second = StudentTable(name='Luke', surname='Skywalker')

    teacher = TeacherTable(name='Obi Wan', surname='Kenobi')

    homework = HomeworkTable(text='Take the force with you',
                             created=datetime.strptime('21:01:10',
                                                       '%y:%m:%d'),
                             final_day=datetime.strptime('21:01:11',
                                                         '%y:%m:%d'),
                             teacher_id=1)

    hw_res_1 = HomeworkResultTable(author=1,
                                   homework=1,
                                   solution='Force is always with me',
                                   created=datetime.strptime('21:01:10',
                                                             '%y:%m:%d'),
                                   status=False)

    hw_res_2 = HomeworkResultTable(author=2,
                                   homework=1,
                                   solution='Make the force to be with you',
                                   created=datetime.strptime('21:01:10',
                                                             '%y:%m:%d'),
                                   status=True)

    session.add_all([student_first, student_second, teacher, homework,
                     hw_res_1, hw_res_2])
    session.flush()
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
