"""
Added tables

Revision ID: d95c0cfd98d9
Revises:
Create Date: 2022-01-09 23:30:16.526272
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd95c0cfd98d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('surname', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('surname', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('homeworks',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('final_day', sa.TIMESTAMP(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('homework_results',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('author', sa.Integer(), nullable=True),
                    sa.Column('homework', sa.Integer(), nullable=True),
                    sa.Column('solution', sa.String(), nullable=True),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('status', sa.BOOLEAN(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], ['students.id'], ),
                    sa.ForeignKeyConstraint(['homework'], ['homeworks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_results')
    op.drop_table('homeworks')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
