PARSE_FIRST_PAGE = 'https://markets.businessinsider.com/index/components/s&p_500'
INITIAL_LINK = 'https://markets.businessinsider.com'

# CSS FOR PARSING
COMPANIES_TABLE = 'table__tbody'
COMPANY = "^/stocks.*stock$"

